name: Analyze

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Notify
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: 'INFO: https://github.com/neronorai/BarsLogger/tree/master/BarsLogger analysys started'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .Net SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.209'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --blame --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=opencover.xml
    - name: Install SonarCloud Tools
      run: dotnet tool install --global dotnet-sonarscanner --version 5.0.209
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Notify
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: 'INFO: https://github.com/neronorai/BarsLogger/tree/master/BarsLogger analysys result [#${{ job.status }}]'