name: build

on:
  push:
    branches: [master]
    paths: [BarsLogger/**]
  pull_request:
    branches: [master]
    paths: [BarsLogger/**]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    #notify
    - name: send alert in telegram
    if: ${{ failure() }}
    uses: appleboy/telegram-action@master
    with:
      to: ${{ secrets.TELEGRAM_CHAT_ID }}
      token: ${{ secrets.TELEGRAM_TOKEN }}
      message: |
        Build failed
    if: ${{ success() }}
    uses: appleboy/telegram-action@master
    with:
      to: ${{ secrets.TELEGRAM_CHAT_ID }}
      token: ${{ secrets.TELEGRAM_TOKEN }}
      message: |
        Build succeeded